# Generated by Django 4.2.2 on 2023-07-01 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('phone_number', models.CharField(max_length=20)),
                ('bmi_value', models.IntegerField()),
                ('refid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
