# Generated by Django 4.2.2 on 2023-07-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bmi_value',
            field=models.FloatField(),
        ),
    ]
