# Generated by Django 4.2.2 on 2023-07-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_person_bmi_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=30),
        ),
    ]
